// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gorm.proto

package gorm

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Protobuf struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Protobuf) Reset()         { *m = Protobuf{} }
func (m *Protobuf) String() string { return proto.CompactTextString(m) }
func (*Protobuf) ProtoMessage()    {}
func (*Protobuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_gorm_e12c0f332c06e5be, []int{0}
}
func (m *Protobuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protobuf.Unmarshal(m, b)
}
func (m *Protobuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protobuf.Marshal(b, m, deterministic)
}
func (dst *Protobuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protobuf.Merge(dst, src)
}
func (m *Protobuf) XXX_Size() int {
	return xxx_messageInfo_Protobuf.Size(m)
}
func (m *Protobuf) XXX_DiscardUnknown() {
	xxx_messageInfo_Protobuf.DiscardUnknown(m)
}

var xxx_messageInfo_Protobuf proto.InternalMessageInfo

func (m *Protobuf) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Protobuf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_Enabled = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         75000,
	Name:          "gorm.enabled",
	Tag:           "varint,75000,opt,name=enabled",
	Filename:      "gorm.proto",
}

var E_GeneratePrimaryKey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Protobuf)(nil),
	Field:         75001,
	Name:          "gorm.generate_primary_key",
	Tag:           "bytes,75001,opt,name=generate_primary_key,json=generatePrimaryKey",
	Filename:      "gorm.proto",
}

var E_GenerateCreateAt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Protobuf)(nil),
	Field:         75002,
	Name:          "gorm.generate_create_at",
	Tag:           "bytes,75002,opt,name=generate_create_at,json=generateCreateAt",
	Filename:      "gorm.proto",
}

var E_GenerateUpdateAt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Protobuf)(nil),
	Field:         75003,
	Name:          "gorm.generate_update_at",
	Tag:           "bytes,75003,opt,name=generate_update_at,json=generateUpdateAt",
	Filename:      "gorm.proto",
}

var E_GenerateDeleteAt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Protobuf)(nil),
	Field:         75004,
	Name:          "gorm.generate_delete_at",
	Tag:           "bytes,75004,opt,name=generate_delete_at,json=generateDeleteAt",
	Filename:      "gorm.proto",
}

var E_PrimaryKey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         76001,
	Name:          "gorm.primary_key",
	Tag:           "varint,76001,opt,name=primary_key,json=primaryKey",
	Filename:      "gorm.proto",
}

var E_CreateAt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         76002,
	Name:          "gorm.create_at",
	Tag:           "varint,76002,opt,name=create_at,json=createAt",
	Filename:      "gorm.proto",
}

var E_UpdateAt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         76003,
	Name:          "gorm.update_at",
	Tag:           "varint,76003,opt,name=update_at,json=updateAt",
	Filename:      "gorm.proto",
}

var E_DeleteAt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         76004,
	Name:          "gorm.delete_at",
	Tag:           "varint,76004,opt,name=delete_at,json=deleteAt",
	Filename:      "gorm.proto",
}

func init() {
	proto.RegisterType((*Protobuf)(nil), "gorm.protobuf")
	proto.RegisterExtension(E_Enabled)
	proto.RegisterExtension(E_GeneratePrimaryKey)
	proto.RegisterExtension(E_GenerateCreateAt)
	proto.RegisterExtension(E_GenerateUpdateAt)
	proto.RegisterExtension(E_GenerateDeleteAt)
	proto.RegisterExtension(E_PrimaryKey)
	proto.RegisterExtension(E_CreateAt)
	proto.RegisterExtension(E_UpdateAt)
	proto.RegisterExtension(E_DeleteAt)
}

func init() { proto.RegisterFile("gorm.proto", fileDescriptor_gorm_e12c0f332c06e5be) }

var fileDescriptor_gorm_e12c0f332c06e5be = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xc9, 0x47, 0xbe, 0xda, 0x9c, 0x82, 0x48, 0x14, 0x29, 0x8a, 0x18, 0x5c, 0x75, 0x95,
	0x82, 0x82, 0x8b, 0xd8, 0x85, 0xad, 0xa2, 0x0b, 0x29, 0x95, 0x80, 0xeb, 0x90, 0x64, 0x4e, 0x43,
	0x30, 0xc9, 0x0c, 0x93, 0xc9, 0xa2, 0x97, 0xe8, 0xd2, 0x4b, 0xf0, 0xe7, 0x22, 0xfc, 0x5b, 0x48,
	0x27, 0x1d, 0xa3, 0x15, 0x99, 0xae, 0x32, 0x73, 0x92, 0xf7, 0x79, 0x38, 0x6f, 0x00, 0x12, 0xca,
	0x73, 0x97, 0x71, 0x2a, 0xa8, 0x6d, 0xce, 0xcf, 0x3b, 0x4e, 0x42, 0x69, 0x92, 0x61, 0x5f, 0xce,
	0xa2, 0x6a, 0xda, 0x27, 0x58, 0xc6, 0x3c, 0x65, 0x82, 0xf2, 0xfa, 0xbb, 0x83, 0x63, 0x68, 0xab,
	0x97, 0xf6, 0x36, 0xb4, 0x8a, 0x2a, 0x8f, 0x90, 0x77, 0x0d, 0xc7, 0xe8, 0xfd, 0xf7, 0x17, 0x37,
	0xdb, 0x06, 0xb3, 0x08, 0x73, 0xec, 0xfe, 0x73, 0x8c, 0x9e, 0xe5, 0xcb, 0xb3, 0x77, 0x02, 0x6b,
	0x58, 0x84, 0x51, 0x86, 0xc4, 0xde, 0x77, 0x6b, 0x8b, 0xab, 0x40, 0xee, 0x18, 0xcb, 0x32, 0x4c,
	0x70, 0xc2, 0x44, 0x4a, 0x8b, 0xb2, 0xfb, 0x72, 0x67, 0x3a, 0x46, 0xaf, 0xed, 0xab, 0x84, 0x17,
	0xc3, 0x56, 0x82, 0x05, 0xf2, 0x50, 0x60, 0xc0, 0x78, 0x9a, 0x87, 0x7c, 0x16, 0xdc, 0xe2, 0x4c,
	0x4f, 0x7a, 0x95, 0xa4, 0xce, 0xe1, 0xba, 0xdb, 0xac, 0x1a, 0x55, 0x53, 0xdf, 0x56, 0xb8, 0xeb,
	0x9a, 0x76, 0x85, 0x33, 0x2f, 0x80, 0xaf, 0x69, 0x10, 0x73, 0x9c, 0x3f, 0x42, 0xa1, 0x57, 0xbc,
	0xfd, 0xa1, 0xd8, 0x50, 0xb0, 0x33, 0xc9, 0x1a, 0x8a, 0x1f, 0x82, 0x8a, 0x91, 0x55, 0x05, 0xef,
	0x3a, 0xc1, 0x8d, 0x64, 0x2d, 0x09, 0x08, 0x66, 0xb8, 0xa2, 0xe0, 0x43, 0x27, 0x38, 0x97, 0xac,
	0xa1, 0xf0, 0x4e, 0xa1, 0xf3, 0xbd, 0xfe, 0xbd, 0x5f, 0xe4, 0x8b, 0x14, 0x33, 0xa2, 0xb8, 0x0f,
	0xf7, 0xf5, 0x6f, 0x04, 0xd6, 0x94, 0x3c, 0x00, 0xab, 0xe9, 0x56, 0x93, 0x7f, 0x5c, 0xe4, 0xdb,
	0xb1, 0x6a, 0x70, 0x00, 0x56, 0x53, 0x9c, 0x26, 0xfd, 0xa4, 0xd2, 0x95, 0xaa, 0x67, 0x00, 0x56,
	0xd3, 0x8a, 0x26, 0xfd, 0xac, 0xd2, 0x64, 0xb1, 0xfb, 0x68, 0x17, 0x36, 0x63, 0x9a, 0x2f, 0xa7,
	0x46, 0xe6, 0xe5, 0xc4, 0x1f, 0x47, 0x2d, 0x79, 0x3f, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x85, 0x5b, 0x29, 0x52, 0x03, 0x00, 0x00,
}
